# Generated by Django 4.1.7 on 2023-03-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.FloatField(blank=True, max_length=250, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifPostedSalesInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('inv_total_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csv')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FromStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedPhysicalStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('issuedQuantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issuedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('receivedQuantity', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unitcost', models.FloatField(blank=True, default=0, null=True)),
                ('unitPrice', models.IntegerField(default=0, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('receivedQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('receivedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('issuedQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issuedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('issuedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('reorderLevel', models.IntegerField(blank=True, default='0', null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('expiryDate', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('uplift', models.FloatField(blank=True, default=1, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeitemrelated', to='stockmanagementapp.physicalstockmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_order_no', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_store', to='stockmanagementapp.storesmodel')),
                ('to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_store', to='stockmanagementapp.storesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransferOderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toitemrelatedtest', to='stockmanagementapp.storeitemsmodel')),
                ('testtoitemsconnector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toitemrelatedtest', to='stockmanagementapp.transferordersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransferingStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('store', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagementapp.fromstoremodel')),
            ],
        ),
        migrations.AddField(
            model_name='storeitemsmodel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemstorerelatname', to='stockmanagementapp.storesmodel'),
        ),
        migrations.CreateModel(
            name='ReceivingStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('store', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagementapp.tostoremodel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unitcost', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitemrelatedname', to='stockmanagementapp.physicalstockmodel')),
                ('po_item_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitrelname', to='stockmanagementapp.purchaseordersmodel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supitemrelname', to='allifmaalapp.allifmaalsuppliersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days')], default='Cash', max_length=100)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Current', 'Current'), ('Overdue', 'Overdue')], default='Current', max_length=100)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='$', max_length=100)),
                ('comments', models.CharField(blank=True, default='invoice', max_length=250, null=True)),
                ('posted', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invcustrelname', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifInvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invstkrelname', to='stockmanagementapp.physicalstockmodel')),
                ('invitemcon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitrelnme', to='stockmanagementapp.allifinvoicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifCustomersBalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('customer', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='clibalrelnam', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifCustomerPaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='payclientrelname', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
    ]
