# Generated by Django 4.1.7 on 2023-03-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalBanksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('account', models.CharField(blank=True, max_length=15, null=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalChartOfAccountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('statement', models.CharField(blank=True, choices=[('Income Statement', 'Income Statement'), ('Balance Sheet', 'Balance Sheet')], max_length=20, null=True)),
                ('nature', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Both', 'Both')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('Posting', 'Posting'), ('Heading', 'Heading'), ('Total', 'Total'), ('Begin-Total', 'Begin-Total'), ('End-Total', 'End-Total')], max_length=20, null=True)),
                ('posting', models.CharField(blank=True, choices=[('sale', 'sale'), ('purchase', 'purchase')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalCustomersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Somalia', 'Somalia'), ('Somaliland', 'Somaliland'), ('Kenya', 'Kenya'), ('Other', 'Other')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('sales', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('turnover', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('pobox', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('phone1', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('phone2', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalGeneralLedgersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalHumanResourcesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffNo', models.IntegerField(blank=True, default='0', null=True, unique=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('staffImage', models.ImageField(blank=True, null=True, upload_to='hrmapp/images/staff/%Y/')),
                ('staffGender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('dateJoined', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalScopeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalStockCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalStocksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('buyingPrice', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('unitcost', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('standardUnitCost', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('unitPrice', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catinvtconrlnm', to='allifmaalapp.allifmaalstockcategoriesmodel')),
                ('expense_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnm', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('income_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaincomerelnm', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('inventory_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coainvrelnm', to='allifmaalapp.allifmaalchartofaccountsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalSuppliersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('Somalia', 'Somalia'), ('Somaliland', 'Somaliland'), ('Kenya', 'Kenya'), ('Other', 'Other')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('turnover', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDrawingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawcoareln', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('fromacc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawcoarcash', to='allifmaalapp.allifmaalchartofaccountsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ForLearningOnlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitemrallirelnmtesting', to='allifmaalapp.allifmaalstocksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('taskDay', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('assignedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskassignrelname', to='allifmaalapp.allifmaalhumanresourcesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalQuotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('terms', models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('prospect', models.CharField(choices=[('Default', 'Default'), ('Likely', 'Likely'), ('Confirmed', 'Confirmed'), ('Closed', 'Closed'), ('Lost', 'Lost')], default='Default', max_length=20)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='$', max_length=20)),
                ('comments', models.CharField(blank=True, default='Quote', max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustquote', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalQuoteItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('allifquoteitemconnector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifquoteitemrelated', to='allifmaalapp.allifmaalquotesmodel')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifquoteitemdescrelatednm', to='allifmaalapp.allifmaalstocksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalPurchaseOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('uplift', models.DecimalField(decimal_places=1, default=2, max_digits=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('posting_po_status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=100, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplporelnme', to='allifmaalapp.allifmaalsuppliersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalPurchaseOrderMiscCostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('po_misc_cost_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomiscrlnm', to='allifmaalapp.allifmaalpurchaseordersmodel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppmiscrlnme', to='allifmaalapp.allifmaalsuppliersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalPurchaseOrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('unitcost', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitemrallirelnm', to='allifmaalapp.allifmaalstocksmodel')),
                ('po_item_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitrelname', to='allifmaalapp.allifmaalpurchaseordersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_due_Date', models.DateField(blank=True, null=True)),
                ('invoice_terms', models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days')], default='Cash', max_length=20)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Current', 'Current'), ('Overdue', 'Overdue')], default='Current', max_length=20)),
                ('invoice_currency', models.CharField(choices=[('KES', 'KES'), ('$', 'USD'), ('£', 'EURO')], default='$', max_length=20)),
                ('invoice_comments', models.CharField(blank=True, default='invoice', max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_total', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('posting_inv_status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('posted', 'posted')], default='waiting', max_length=100, null=True)),
                ('invoice_items_total_cost', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifrelatcustinvoice', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalInvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('allifinvitemconnector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allifinvitemrelated', to='allifmaalapp.allifmaalinvoicesmodel')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allidescrelatednm', to='allifmaalapp.allifmaalstocksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=25, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnanemcon', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('pay_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaexprelnamepayto', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expsupprelanmecon', to='allifmaalapp.allifmaalsuppliersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalCustomerPaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='comment', max_length=15, null=True)),
                ('mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifcustpymaccrelnm', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allifcustpaymentreltedname', to='allifmaalapp.allifmaalcustomersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='allifmaalchartofaccountsmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaglrelname', to='allifmaalapp.allifmaalgeneralledgersmodel'),
        ),
        migrations.CreateModel(
            name='AllifmaalBankWithdrawalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='Withdrawal', max_length=15, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawbankreln', to='allifmaalapp.allifmaalbanksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalBankDepositsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('comments', models.CharField(blank=True, default='Deposit', max_length=15, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositbankreln', to='allifmaalapp.allifmaalbanksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllifmaalAssetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('description', models.CharField(max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('lifespan', models.CharField(blank=True, max_length=10, null=True)),
                ('acquired', models.DateField(blank=True, null=True)),
                ('asset_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetcoareln', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('cost_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcoareln', to='allifmaalapp.allifmaalchartofaccountsmodel')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplporelnmeasset', to='allifmaalapp.allifmaalsuppliersmodel')),
            ],
        ),
    ]
